# Generated by Django 5.0.1 on 2026-01-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='business_registration',
            field=models.CharField(blank=True, help_text='Business registration number', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax ID/VAT number', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='has_completed_setup',
            field=models.BooleanField(default=False, help_text='Whether the user has completed initial setup'),
        ),
    ]
