# Generated by Django 5.0.1 on 2026-01-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_store_options_store_address_store_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={},
        ),
        migrations.AlterModelTable(
            name='store',
            table=None,
        ),
    ]
