# Generated by Django 5.0.1 on 2026-01-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_store_business_registration_store_tax_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['b_name']},
        ),
        migrations.RemoveIndex(
            model_name='medicine',
            name='medicines_name_017048_idx',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='name',
            new_name='b_name',
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['b_name'], name='medicines_b_name_f2b53e_idx'),
        ),
    ]
