# Generated by Django 5.0.1 on 2026-01-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_medicine_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='cost_price',
            new_name='buying_price',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='price',
            new_name='selling_price',
        ),
    ]
